### ISSUE TITLE
Update of dataset all viruses

### ISSUE THREAD

**Issue by jhayer** [broadinstitute/catch#34]
Hi,

Thanks for this tool!
I would like to design probes for capturing viruses infecting humans. I am planning to use your dataset V-all. I see that the sequences are from a pull from October 2018. I wanted to know if it would be possible for you to update this?
Thanks!
Juliette

**Comment by haydenm** [comment]
Hi Juliette,

I'm glad you think CATCH could be useful!

I'm no longer updating the datasets included in CATCH and will deprecate that input method over the coming months. Instead, I think the better path forward is using the `download:TAXID` method to specify input species; this will automatically fetch the latest genomes from NCBI for you when you run CATCH. This is described in the README [here](https://github.com/broadinstitute/catch#designing-with-one-choice-of-parameters-designpy). It's similar to using the provided datasets (although does require you to curate a list of NCBI taxonomy IDs for the different species), except always up-to-date. It's also the method I've been using to design probe sets over the past year.

I'd also note that the V-All probe sets available [here](https://github.com/broadinstitute/catch/tree/master/probe-designs) designed in late 2018 should still be useful for many broad applications, unless there are specific applications you have in mind that involve either novel viral species or subspecies (e.g., SARS-CoV-2) or viruses with high drift over time (e.g., influenza).

Let me know if you have any questions about this or how to use that method.

Hayden
